CoffeeShop/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CoffeeShop.Models;
using IdentitySample.Models;

namespace CoffeeShop.Controllers
{
    [Authorize, Authorize(Roles = "Admin")]

    public class GroupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Groups
        public ActionResult Index()
        {
            return View(db.Group.ToList());
        }
        [Authorize, Authorize(Roles = "Admin")]
        // GET: Groups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Group.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }
        [Authorize, Authorize(Roles = "Admin")]
        // GET: Groups/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize, Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Group.Add(group);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(group);
        }
        [Authorize, Authorize(Roles = "Admin")]
        // GET: Groups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Group.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize, Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Entry(group).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(group);
        }
        [Authorize, Authorize(Roles = "Admin")]
        // GET: Groups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Group.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }
        [Authorize, Authorize(Roles = "Admin")]
        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Group group = db.Group.Find(id);
            db.Group.Remove(group);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CoffeeShop/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CoffeeShop.Models;
using IdentitySample.Models;
using Microsoft.AspNet.Identity.Owin;
using PagedList;

namespace CoffeeShop.Controllers
{
   
    public class ProductsController : Controller
    {
        private ApplicationUserManager _userManager;

        public ProductsController()
        {
            

        }
        public ProductsController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
          
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }


        private ApplicationDbContext db = new ApplicationDbContext();
        [AllowAnonymous]
        // GET: Products
        public ActionResult Index(int group, int? page,string sortoption)
        {
            var pageNumber = page ?? 1;
            var product = db.Product.Include(p => p.Group).Where(x=> x.GroupId == group);

            if (!string.IsNullOrEmpty(sortoption))
            {
                if(sortoption == "1")
                {
                    product = product.OrderBy(x => x.Price);
                }

                if (sortoption == "2")
                {
                    product = product.OrderByDescending(x => x.Price);
                }


            }

            else
            {
                product = product.OrderBy(x => x.ID);
            }


            return View(product.ToPagedList(pageNumber, 3));
        }
        
        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
        [Authorize, Authorize(Roles = "Admin")]
        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.GroupId = new SelectList(db.Group, "ID", "Name");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize, Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Price,Image,GroupId")] Product product, HttpPostedFileBase productImage)
        {
           
            if (productImage != null)
            {
                var allowedExtensions = new[]
                {
                    ".Jpg",".png", ".jpg", "jpeg", ".JPG",".eps"
                };

                var filename = Path.GetFileName(productImage.FileName);
                var ext = Path.GetExtension(productImage.FileName);
                if (allowedExtensions.Contains(ext))
                {
                     var path = Path.Combine(Server.MapPath("~/Images"), filename);
                     productImage.SaveAs(path);
                     product.Image = "../../Images/" + filename;
                }

            }                
            if (ModelState.IsValid)
            {
               db.Product.Add(product);
               db.SaveChanges();
               return RedirectToAction("Index");
            }

            ViewBag.GroupId = new SelectList(db.Group, "ID", "Name", product.GroupId);
            return View(product);
            }
        [Authorize, Authorize(Roles = "Admin")]
        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.GroupId = new SelectList(db.Group, "ID", "Name", product.GroupId);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize, Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Price,Image,GroupId")] Product product, HttpPostedFileBase productImage ,string Imagebeforeedit)
        {
            if (ModelState.IsValid)
            {
                if (productImage != null)
                {
                    var allowedExtensions = new[]
                    {
                    ".Jpg",".png", ".jpg", "jpeg", ".JPG"
                };

                    var filename = Path.GetFileName(productImage.FileName);
                    var ext = Path.GetExtension(productImage.FileName);
                    if (allowedExtensions.Contains(ext))
                    {
                        var path = Path.Combine(Server.MapPath("~/Images"), filename);
                        productImage.SaveAs(path);
                        product.Image = "../../Images/" + filename;
                    }

                }
                else
                {
                    product.Image = Imagebeforeedit;
                }



                db.Entry(product).State = EntityState.Modified;
               db.SaveChanges();
                return RedirectToAction("Index");
                }
                ViewBag.GroupId = new SelectList(db.Group, "ID", "Name", product.GroupId);
                return View(product);
            }

        [Authorize, Authorize(Roles = "Admin")]
        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [Authorize, Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Product.Find(id);
            db.Product.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        [AllowAnonymous]

        public ActionResult AddToCart(int pid)
        {
            var product = db.Product.Find(pid);
            
            //هیچ محصولی به سبد اضافه نشده
            if (Session["shoppingcart"] == null)
            {
                List<shoppingcartViewModels> product_list = new List<shoppingcartViewModels>();
                product_list.Add(new shoppingcartViewModels {Product = product,quantity=1});
                Session["shoppingcart"] = product_list;
            }

            //قبلا محصولی ثبت شده
            else
            {
                bool exist = false;
                var product_list = Session["shoppingcart"] as List<shoppingcartViewModels>;
                foreach (var item in product_list)
                {
                    if(item.Product.ID == product.ID)
                    {
                        //محصول وجود دارد
                        item.quantity = item.quantity + 1;
                        exist = true;
                    }
                }

                if (!exist)
                {
                    product_list.Add(new shoppingcartViewModels { Product = product, quantity = 1 });
                }
               
                Session["shoppingcart"] = product_list;
            }

            return RedirectToAction("shoppingcart");
            
           
        }
         public ActionResult shoppingcart(string status)
        {
            int totalprice = 0;
            List<shoppingcartViewModels> product_list = new List<shoppingcartViewModels>();
            if (Session["shoppingcart"] !=null)
            {
                product_list = Session["shoppingcart"] as List<shoppingcartViewModels>;
                foreach (var item in product_list)
                {
                    totalprice = totalprice + (item.Product.Price * item.quantity);
                }
            }
            ViewBag.status = status;
            ViewBag.totalprice = totalprice;
            return View(product_list); 
        }


        public ActionResult DeleteItemFromCart(int pid)
        {
            var product_list = Session["shoppingcart"] as List<shoppingcartViewModels>;
            var product = product_list.Where(x => x.Product.ID == pid).FirstOrDefault();
            product_list.Remove(product);
            Session["shoppingcart"] = product_list;
            return RedirectToAction("shoppingcart");
        }

        public ActionResult increasequantity(int pid)
        {
            var product_list = Session["shoppingcart"] as List<shoppingcartViewModels>;
            foreach(var item in product_list)
            {
                if (item.Product.ID == pid){

                    item.quantity = item.quantity + 1;
                }
            }
            Session["shoppingcart"] = product_list;
            return RedirectToAction("shoppingcart");
        }


        public ActionResult decreasequantity(int pid)
            {

CoffeeShop/Views/Shared/_AdminLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<!-- Side navigation -->
    <div class="sidenav">
        <a href="@Url.Action("Index","Groups")">Groups</a>
        <a href="@Url.Action("Index","Products")"> I Products</a>
       
    </div>

<!-- Page content -->
<div class="main">
  @RenderBody()
</div>

CoffeeShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>

    <header class="headers">
        <div class="head_div">
            <div class="head_div_right">

                <div class="grp-div">

                    <label class="wellcome">خوش آمدید </label>

                    <label id="pdate" class="pdate"></label>
                    <script src="/pdate.min.js"></script>
                    <script type="text/javascript">AMIB.showPDate('pdate');</script>
                </div>

            </div>

            <div class="head_div_left">

                <img class="img-logo" src="/logo.jpg" width="110" height="80" />

            </div>
        </div>
    </header>


    <div class="navbar navbar-inverse ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @Html.ActionLink("COFFEE SHOP", "Index", "Home", null, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                @Html.Action("_nav_partial", "Home")
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

     

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CoffeeShop/Views/Shared/_nav_partial.cshtml
@model IEnumerable<CoffeeShop.Models.Group>





    <ul class="nav navbar-nav   group-nav" dir="rtl">


        <li><a href="@Url.Action("shoppingcart","Products") ">سبدخرید  @Html.Action("itemcount", "Products")   <img  src="~/Images/shopping_cart.png" /></a></li>
        

        <li class="dropdown">

            <a class="dropdown-toggle" data-toggle="dropdown">
                همه ی گروه ها
                <span class="caret"></span>
            </a>

            <ul class="dropdown-menu">


                <li class="grop-c"><a class="nav-link" href="@Url.Action("Index", "Products", new { group = 1 })">صبحانه</a></li>
                <li class="grop-c"><a class="nav-link" href="@Url.Action("Index", "Products", new { group =2 })">نوشیدنی</a></li>
                <li class="grop-c"><a class="nav-link" href="@Url.Action("Index", "Products", new { group = 3 })">بستنی</a></li>
                <li class="grop-c"><a class="nav-link" href="@Url.Action("Index", "Products", new { group = 4 })">گلاسه</a></li>
                <li class="grop-c"><a class="nav-link" href="@Url.Action("Index", "Products", new { group = 5 })">پیش غذا</a></li>
                <li class="grop-c"><a class="nav-link" href="@Url.Action("Index", "Products", new { group = 6 })">ساندویچ</a></li>
                <li class="grop-c"><a class="nav-link" href="@Url.Action("Index", "Products", new { group = 7 })">پیتزا</a></li>
                <li class="grop-c"><a class="nav-link" href="@Url.Action("Index", "Products", new { group =8 })">سوخاری</a></li>
                <li class="grop-c"><a class="nav-link" href="@Url.Action("Index", "Products", new { group =9 })">کیک</a></li>

            </ul>
        </li>

    </ul>




























@*@if (Request.IsAuthenticated && User.IsInRole("Admin"))
    {
        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
    }*@

CoffeeShop/Views/Shared/itemcount.cshtml
@ViewBag.count